### ISSUE TITLE
Missing padding field in marshalling and unmarshalling ElectronicEmitter

### ISSUE THREAD

**Issue by austinarrowsmith** [open-dis/opendis7-source-generator#12]
If I understand correctly, I believe the ElectronicEmitter class is missing a 16-bit/2-byte padding field between `numberOfBeams` and `emitterSystem` that is missed during (un)marshalling ([ref](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/b9.htm)):

ie:
```java
public int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    try 
    {
        systemDataLength = (byte)dis.readUnsignedByte();
        uPosition += 1;
        numberOfBeams = (byte)dis.readUnsignedByte();
        uPosition += 1;
        dis.readUnsignedShort(); // missing this 2-byte padding buffer.
        uPosition += 2;
        uPosition += emitterSystem.unmarshal(dis);
        uPosition += location.unmarshal(dis);
        for(int idx = 0; idx < numberOfBeams; idx++)
.
.
.
```
... and in here:
```java
public void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   byteBuffer.put( (byte)systemDataLength);
   byteBuffer.put( (byte)beams.size());
   byteBuffer.putShort((short)0); // needs to insert the (empty) padding field of the PDU.
   emitterSystem.marshal(byteBuffer);
   location.marshal(byteBuffer);
.
.
.
```
... and in the corresponding `ByteBuffer` methods for marshalling and unmarshalling too.

**Comment by terry-norbraten** [comment]
I have confirmed that the 16-bit padding field is indeed missing from both marshaling/unmarshaling methods in the ElectronicEmitter class.

**Comment by brutzman** [comment]
@terry-norbraten confirmed corrected.  Suggest adding comprehensive padding tests in the future.
