### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by rickbatka** [open-dis/opendis7-source-generator#2]
Hi! 

I used the generated C++ bindings from `open-dis-cpp` to get started on a project and they work great! But I need some changes. So I was just about to fork XMLPG and start making the changes I need, but then I found this project.

1. I gather this project intends to replace XMLPG but is still in development. Is that right?
1. The README in this repository only describes generating Java code, but there exist generators for other languages. Which languages are supported?
1. What is the state of the project for generating C++? Should I just continue with the XMLPG for now, if I need C++ marshaling / un-marshaling for DIS messages?

Thanks so much, and congrats on the useful libraries!

**Comment by terry-norbraten** [comment]
Hello Rick,

The current open dis 7 project does not yet generate C++, or any other language bindings, only java as you have stated.

Best to use the older XMLPG to make any changes you wish.

Best,

Terry

**Comment by rickbatka** [comment]
Thanks, Terry! I will move forward using that code generator. Thanks for clearing this up.
