### ISSUE TITLE
Unsafe equalsImpl for object list attributes

### ISSUE THREAD

**Issue by salmariii** [open-dis/opendis7-source-generator#8]
Generated equalsImpl methods do unsafe checks for OBJECT_LIST type attributes. Method will throw _IndexOutOfBoundsException_ when other object list is shorter that this object list. Equals method should not throw exceptions, list sizes should be compared before trying to access variables in the list.

**Comment by brutzman** [comment]
Thank you for this report. When convenient please identify an example class/method with code snippet to help ensure that we address the correct code blocks.

**Comment by terry-norbraten** [comment]
![Screen Shot 2023-11-28 at 15 22 08](https://github.com/open-dis/opendis7-source-generator/assets/6370489/34db000f-6808-429f-ae79-8a784b6a68ee)
![Screen Shot 2023-11-28 at 15 22 32](https://github.com/open-dis/opendis7-source-generator/assets/6370489/ec106521-f7cb-4c4b-9409-19b37cff7da9)
![Screen Shot 2023-11-28 at 15 22 54](https://github.com/open-dis/opendis7-source-generator/assets/6370489/e23fac2b-dd59-403a-bfa8-37e4def989bb)

**Comment by salmariii** [comment]
Solution to this issue can be found here: https://github.com/arttu-salminen-insta-fi/opendis7-source-generator/commit/91707b217fccab938183b29685d5611c02987a48 . This solution also provides null safe equals checks to SISO_BITFIELD and CLASSREF types while increasing the performance of equals checks. We'll create a pull request to this project.

**Comment by salmariii** [comment]
We've added solution to this issue to a previous pull request: https://github.com/open-dis/opendis7-source-generator/pull/15

**Comment by brutzman** [comment]
Implemented as part of pull request.
